/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.appclinica.Presentation;

/**
 *
 * @author Samuel Castaño, Alejandro Toro y Hector Ospina
 */
public class AcercaDeDialog extends javax.swing.JDialog {

    /**
     * Creates new form AcercaDeDialog
     */
    public AcercaDeDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAutores = new javax.swing.JLabel();
        autor1 = new javax.swing.JLabel();
        autor2 = new javax.swing.JLabel();
        autor3 = new javax.swing.JLabel();
        autor4 = new javax.swing.JLabel();
        autor5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textDescripcion = new javax.swing.JTextArea();
        buttonCerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelAppClinica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelAutores.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelAutores.setForeground(new java.awt.Color(46, 71, 86));
        labelAutores.setText("Autores:");

        autor1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        autor1.setForeground(new java.awt.Color(46, 71, 86));
        autor1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor1.setText("Juan Manuel Moscoso Torres");
        autor1.setToolTipText("");

        autor2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        autor2.setForeground(new java.awt.Color(46, 71, 86));
        autor2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor2.setText("Slleider David Rojas Aleman");
        autor2.setToolTipText("");

        autor3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        autor3.setForeground(new java.awt.Color(46, 71, 86));
        autor3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor3.setText("Samuel Castaño Arenas");
        autor3.setToolTipText("");

        autor4.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        autor4.setForeground(new java.awt.Color(46, 71, 86));
        autor4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor4.setText("Alejandro Toro Bueno");
        autor4.setToolTipText("");

        autor5.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        autor5.setForeground(new java.awt.Color(46, 71, 86));
        autor5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        autor5.setText("Héctor Julian Ospina");
        autor5.setToolTipText("");

        textDescripcion.setColumns(20);
        textDescripcion.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        textDescripcion.setRows(5);
        textDescripcion.setText("Aplicación de escritorio para gestionar \nlas consultas médicas en una clínica. \nPermitiendo registrar pacientes, médicos, \nespecialidades, agendar citas, y llevar un \nhistorial básico de consultas.");
        jScrollPane1.setViewportView(textDescripcion);

        buttonCerrar.setBackground(new java.awt.Color(220, 53, 69));
        buttonCerrar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        buttonCerrar.setForeground(new java.awt.Color(255, 255, 255));
        buttonCerrar.setText("Cerrar");
        buttonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCerrarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(30, 107, 117));

        labelAppClinica.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        labelAppClinica.setForeground(new java.awt.Color(255, 255, 255));
        labelAppClinica.setText("App Clinica v1.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelAppClinica)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(labelAppClinica, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(274, 274, 274))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(autor2)
                                .addComponent(autor1)
                                .addComponent(autor3)
                                .addComponent(autor4)
                                .addComponent(autor5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(buttonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(autor1)
                    .addComponent(labelAutores, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autor2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autor3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autor4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autor5)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(buttonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcercaDeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcercaDeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcercaDeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcercaDeDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AcercaDeDialog dialog = new AcercaDeDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel autor1;
    private javax.swing.JLabel autor2;
    private javax.swing.JLabel autor3;
    private javax.swing.JLabel autor4;
    private javax.swing.JLabel autor5;
    private javax.swing.JButton buttonCerrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelAppClinica;
    private javax.swing.JLabel labelAutores;
    private javax.swing.JTextArea textDescripcion;
    // End of variables declaration//GEN-END:variables
}
