/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appclinica.Presentation;

import com.mycompany.appclinica.Models.Paciente;
import com.mycompany.appclinica.Services.PacienteService;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Slleider
 */
public class ListaPaciente extends javax.swing.JInternalFrame {
    private PacienteService pacienteService;
    /**
     * Creates new form ListaPaciente
     * @param pacienteService
     */
    public ListaPaciente(PacienteService pacienteService) {
        this.pacienteService = pacienteService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        labelMedicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatosMedicos = new javax.swing.JTable();
        buttonCrear = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();
        buttonRefresacar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        textFieldBuscar = new javax.swing.JTextField();
        labelPaciente = new javax.swing.JLabel();
        buttonCrear2 = new javax.swing.JButton();
        buttonBuscar2 = new javax.swing.JButton();
        buttonRefresacar2 = new javax.swing.JButton();
        buttonVerCitas = new javax.swing.JButton();
        buttonEditar2 = new javax.swing.JButton();
        textFieldBuscar2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDatosPaciente = new javax.swing.JTable();
        buttonEliminar2 = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        labelMedicos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        labelMedicos.setText("Médicos");

        tableDatosMedicos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        tableDatosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Especialidad"
            }
        ));
        jScrollPane1.setViewportView(tableDatosMedicos);

        buttonCrear.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonRefresacar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonRefresacar.setText("Refrescar");
        buttonRefresacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefresacarActionPerformed(evt);
            }
        });

        buttonEliminar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonEditar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEditar.setText("Editar");

        textFieldBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        textFieldBuscar.setText("Buscar");
        textFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonRefresacar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(labelMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMedicos)
                    .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRefresacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
        );

        labelPaciente.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        labelPaciente.setText("Paciente");

        buttonCrear2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonCrear2.setText("Crear");
        buttonCrear2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrear2ActionPerformed(evt);
            }
        });

        buttonBuscar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonBuscar2.setText("Buscar");
        buttonBuscar2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscar2ActionPerformed(evt);
            }
        });

        buttonRefresacar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonRefresacar2.setText("Refrescar");
        buttonRefresacar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefresacar2ActionPerformed(evt);
            }
        });

        buttonVerCitas.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonVerCitas.setText("Ver Citas");
        buttonVerCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVerCitasActionPerformed(evt);
            }
        });

        buttonEditar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEditar2.setText("Editar");
        buttonEditar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditar2ActionPerformed(evt);
            }
        });

        textFieldBuscar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        textFieldBuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscar2ActionPerformed(evt);
            }
        });

        tableDatosPaciente.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        tableDatosPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Fecha de Nacimiento"
            }
        ));
        jScrollPane2.setViewportView(tableDatosPaciente);

        buttonEliminar2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEliminar2.setText("Eliminar");
        buttonEliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminar2ActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jButtonSalir.setText("x");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Ingrese la cédula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonEditar2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(textFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37)
                                    .addComponent(buttonBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(463, 463, 463)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(buttonRefresacar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPaciente)
                        .addGap(550, 550, 550)
                        .addComponent(jButtonSalir)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonSalir)
                    .addComponent(labelPaciente))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCrear2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonRefresacar2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonBuscar2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonEditar2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonVerCitas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonEliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonRefresacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefresacarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonRefresacarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void textFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarActionPerformed

    private void buttonCrear2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrear2ActionPerformed
        FormularioPacientes form = new FormularioPacientes(pacienteService, null);
        getParent().add(form); // Abrir en el desktopPane
        form.setVisible(true);
    }//GEN-LAST:event_buttonCrear2ActionPerformed

    private void buttonBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscar2ActionPerformed
        String texto = textFieldBuscar2.getText().trim();
        List<Paciente> resultados;

        if (texto.matches("\\d+")) {
            // Si es solo números, buscar por cédula
            Optional<Paciente> p = pacienteService.buscarPorCedula(texto);
            resultados = new ArrayList<>();
            if (p.isPresent()) {
                resultados.add(p.get());
            }
        } else {
            // Sino buscar por nombre
            resultados = pacienteService.buscarPorNombre(texto);
        }

        DefaultTableModel model = (DefaultTableModel) tableDatosPaciente.getModel();
        model.setRowCount(0);

        for (Paciente p : resultados) {
            model.addRow(new Object[]{
                p.getCedula(),
                p.getNombre(),
                p.getApellido(),
                p.getTelefono(),
                p.getFechaNacimiento()
            });
        }
    }//GEN-LAST:event_buttonBuscar2ActionPerformed

    private void buttonRefresacar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefresacar2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableDatosPaciente.getModel();
        model.setRowCount(0);

        List<Paciente> todosPacientes = pacienteService.listarTodos();

        for (Paciente p : todosPacientes) {
            model.addRow(new Object[]{
                p.getCedula(),
                p.getNombre(),
                p.getApellido(),
                p.getTelefono(),
                p.getFechaNacimiento()
            });
        }
    }//GEN-LAST:event_buttonRefresacar2ActionPerformed

    private void buttonVerCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVerCitasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonVerCitasActionPerformed

    private void textFieldBuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscar2ActionPerformed

    private void buttonEliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminar2ActionPerformed
        int fila = tableDatosPaciente.getSelectedRow();
        if (fila != -1) {
            String cedula = (String) tableDatosPaciente.getValueAt(fila, 0);
            pacienteService.eliminarPaciente(cedula);
            JOptionPane.showMessageDialog(this, "Paciente eliminado");
            buttonRefresacar2ActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente para eliminar");
        }
    }//GEN-LAST:event_buttonEliminar2ActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void buttonEditar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditar2ActionPerformed
        int fila = tableDatosPaciente.getSelectedRow();
        if (fila != -1) {
            String cedula = (String) tableDatosPaciente.getValueAt(fila, 0);
            Optional<Paciente> p = pacienteService.buscarPorCedula(cedula);
            if (p.isPresent()) {
                FormularioPacientes formulario = new FormularioPacientes(pacienteService, p.get());
                getParent().add(formulario);
                formulario.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un paciente para editar");
        }
    }//GEN-LAST:event_buttonEditar2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonBuscar2;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JButton buttonCrear2;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEditar2;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonEliminar2;
    private javax.swing.JButton buttonRefresacar;
    private javax.swing.JButton buttonRefresacar2;
    private javax.swing.JButton buttonVerCitas;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelMedicos;
    private javax.swing.JLabel labelPaciente;
    private javax.swing.JTable tableDatosMedicos;
    private javax.swing.JTable tableDatosPaciente;
    private javax.swing.JTextField textFieldBuscar;
    private javax.swing.JTextField textFieldBuscar2;
    // End of variables declaration//GEN-END:variables
}
