/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.appclinica.Presentation;

import com.mycompany.appclinica.Models.Medico;
import com.mycompany.appclinica.Services.MedicoService;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juan Moscoso y Slleider Rojas
 */
public class ListaMedico extends javax.swing.JInternalFrame {
    private MedicoService medicoService;
    /**
     * Creates new form ListaPacientes
     */
    public ListaMedico(MedicoService medicoService) {
        this.medicoService = medicoService;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        labelMedicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDatosMedicos = new javax.swing.JTable();
        buttonCrear = new javax.swing.JButton();
        buttonBuscar = new javax.swing.JButton();
        buttonRefresacar = new javax.swing.JButton();
        buttonEliminar = new javax.swing.JButton();
        buttonEditar = new javax.swing.JButton();
        textFieldBuscar = new javax.swing.JTextField();
        jButtonSalir3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel1.setText("jLabel1");

        labelMedicos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        labelMedicos.setText("Médicos");

        tableDatosMedicos.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        tableDatosMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cédula", "Nombre", "Apellido", "Teléfono", "Especialidad"
            }
        ));
        jScrollPane1.setViewportView(tableDatosMedicos);

        buttonCrear.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonCrear.setText("Crear");
        buttonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCrearActionPerformed(evt);
            }
        });

        buttonBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonBuscar.setText("Buscar");
        buttonBuscar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        buttonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBuscarActionPerformed(evt);
            }
        });

        buttonRefresacar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonRefresacar.setText("Refrescar");
        buttonRefresacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefresacarActionPerformed(evt);
            }
        });

        buttonEliminar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEliminar.setText("Eliminar");
        buttonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEliminarActionPerformed(evt);
            }
        });

        buttonEditar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        buttonEditar.setText("Editar");
        buttonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditarActionPerformed(evt);
            }
        });

        textFieldBuscar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        textFieldBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldBuscarActionPerformed(evt);
            }
        });

        jButtonSalir3.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 18)); // NOI18N
        jButtonSalir3.setText("x");
        jButtonSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalir3ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Ingrese la cédula:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonRefresacar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(buttonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(labelMedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSalir3))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelMedicos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSalir3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldBuscar, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buttonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonRefresacar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCrearActionPerformed
        FormulariosMedicos form = new FormulariosMedicos(medicoService, null);
        getParent().add(form); // Abrir en el desktopPane
        form.setVisible(true);
    }//GEN-LAST:event_buttonCrearActionPerformed

    private void buttonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBuscarActionPerformed
        String texto = textFieldBuscar.getText().trim();
        List<Medico> resultados;

        if (texto.matches("\\d+")) {
            // Si es solo números, buscar por cédula
            Optional<Medico> m = medicoService.buscarPorCedula(texto);
            resultados = new ArrayList<>();
            if (m.isPresent()) {
                resultados.add(m.get());
            }
        } else {
            // Sino buscar por nombre
            resultados = medicoService.buscarPorNombre(texto);
        }

        DefaultTableModel model = (DefaultTableModel) tableDatosMedicos.getModel();
        model.setRowCount(0);

        for (Medico m : resultados) {
            model.addRow(new Object[]{
                m.getCedula(),
                m.getNombre(),
                m.getApellido(),
                m.getTelefono(),
                m.getEspecialidad()
            });
        }
    }//GEN-LAST:event_buttonBuscarActionPerformed

    private void buttonRefresacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefresacarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tableDatosMedicos.getModel();
        model.setRowCount(0);

        List<Medico> todosMedicos = medicoService.listarTodos();

        for (Medico m : todosMedicos) {
            model.addRow(new Object[]{
                m.getCedula(),
                m.getNombre(),
                m.getApellido(),
                m.getTelefono(),
                m.getEspecialidad()
            });
        }
    }//GEN-LAST:event_buttonRefresacarActionPerformed

    private void buttonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEliminarActionPerformed
        int fila = tableDatosMedicos.getSelectedRow();
        if (fila != -1) {
            String cedula = (String) tableDatosMedicos.getValueAt(fila, 0);
            medicoService.eliminarMedico(cedula);
            JOptionPane.showMessageDialog(this, "Medico eliminado");
            buttonRefresacarActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un medico para eliminar");
        }
    }//GEN-LAST:event_buttonEliminarActionPerformed

    private void textFieldBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldBuscarActionPerformed

    private void jButtonSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalir3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonSalir3ActionPerformed

    private void buttonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditarActionPerformed
        int fila = tableDatosMedicos.getSelectedRow();
        if (fila != -1) {
            String cedula = (String) tableDatosMedicos.getValueAt(fila, 0);
            Optional<Medico> m = medicoService.buscarPorCedula(cedula);
            if (m.isPresent()) {
                FormulariosMedicos formulario = new FormulariosMedicos(medicoService, m.get());
                getParent().add(formulario);
                formulario.setVisible(true);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un medico para editar");
        }
    }//GEN-LAST:event_buttonEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBuscar;
    private javax.swing.JButton buttonCrear;
    private javax.swing.JButton buttonEditar;
    private javax.swing.JButton buttonEliminar;
    private javax.swing.JButton buttonRefresacar;
    private javax.swing.JButton jButtonSalir3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelMedicos;
    private javax.swing.JTable tableDatosMedicos;
    private javax.swing.JTextField textFieldBuscar;
    // End of variables declaration//GEN-END:variables
}
